shell:
	docker exec -it django-app sh -c "poetry shell"

migrate:
	docker exec -it django-app sh -c "poetry run python manage.py migrate"

createsuperuser:
	docker exec -it django-app sh -c "poetry run python manage.py createsuperuser"

